name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install arm toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: thumbv6m-none-eabi
    - name: Build
      run: cargo build --verbose
    - name: Build is no_std compatible
      run: cargo build --verbose --target thumbv6m-none-eabi --no-default-features

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install bevy example dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Run tests
      run: cargo test --verbose
